print ("Welcome to the Bill - Splitter Generator : A Perfect After Party Method to split big Bills")
print ()
Bill = float(input("Enter the Bill Amount: "))
Tip = int(input("Enter the Tip amount (*Note : Generally Tip Amount '10%','12%','15%'): "))
Num_of_People = int(input("Number of Memebers the Bill needed to be split among: "))
print()
Per_Person = round((Bill*(1+(Tip/100)))/Num_of_People,3)
Per_Person = "{:.2f}".format(Per_Person)
print (f"Each Member have to pay :{Per_Person}")
print ("Thank You for Using Us")