import streamlit as st

st.write("# Widget Power of Streamlit")
st.write("## Widgets in Streamlit")

st.slider("Select a number", 0, 100, 50)
st.selectbox("Choose a fruit", ["Apple", "Banana", "Cherry"])
st.checkbox("I agree to the terms and conditions")
st.radio("Select an option", ["Option 1", "Option 2", "Option 3"])
st.text_input("Enter your name")    
st.text_area("Enter your message")
st.button("Click me")
st.file_uploader("Upload a file", type=["jpg", "png", "pdf"])
st.date_input("Select a date")
st.time_input("Select a time")
st.number_input("Enter a number", min_value=0, max_value=100, value=50, step=1)
st.multiselect("Select multiple options", ["Option A", "Option B", "Option C"])
st.select_slider("Select a range", options=["Low", "Medium", "High"], value=("Low", "High"))
st.color_picker("Pick a color", "#00f900")
st.expander("More options", expanded=False)
st.progress(50)
st.spinner("Loading...")
st.success("Operation successful!")
st.error("An error occurred!")
st.warning("This is a warning message.")
st.info("This is an informational message.")
st.markdown("### Markdown Example")