import random, os
from Game_data import data
def system_clean():
    if os.name == 'nt':
        os.system('cls')

LOGO = '''
    __  ___       __             
   / / / (_)___ _/ /_  ___  _____
  / /_/ / / __ `/ __ \/ _ \/ ___/
 / __  / / /_/ / / / /  __/ /    
/_/ ///_/\__, /_/ /_/\___/_/     
        /____/    __
                 / /   _______     _____  _____
                / /   / __ \ | /| / / _ \/ ___/
               / /___/ /_/ / |/ |/ /  __/ /    
              /_____/\____/|__/|__/\___/_/ 
'''
def play_game():
    print (LOGO)
    print ("Who Has More Instagram Follower Version !!")
    print ()
    #The Game Data is Generated by ChatGPT as of 24-07-2024. Apologise for the Inconvience.
    score = 0
    repeated_value = [] #Used to collect all the used indexes so it wont be repeated again.
    while True:
        rand_1 = random.randint(0,len(data)-1)
        rand_2 = random.randint(0,len(data)-1)
        if rand_1 not in repeated_value and rand_2 not in repeated_value:
            #Check the list so no values are repeated for Comparision.
            comparison_1 = data[rand_1]
            print (f"Name: {comparison_1['name']},\nIgn: {comparison_1['ign']}\n{comparison_1['profession']}, {comparison_1['country']}")

            vs = '''
            _    __    
            | |  / /____
            | | / / ___/
            | |/ (__  ) 
            |___/____(_)
            '''
            print (vs)
            comparison_2 = data[rand_2]
            print (f"Name: {comparison_2['name']},\nIgn: {comparison_2['ign']}\n{comparison_2['profession']}, {comparison_2['country']}")

            repeated_value.append(rand_1) #Adding the index to the list
            repeated_value.append(rand_2)
            if (comparison_1['name'] == comparison_2['name']):
                print ()
                print ("Same User Arrived !! Let's Go Again !!")
                repeated_value.pop()    #Poping so it can be used again.
                repeated_value.pop()
                continue
            elif ((data == [])):
                print ("\nYou Scored: 18 !!")
                print ("You are the King !!\nYou Guessed it all Right !!")
                break
            else:
                print ()
                make_a_choice = input("Who Do You Think Has Higher Number Of Followers: 'A' or 'B' ? ")
                if (make_a_choice == "A"):
                    if (comparison_1['follower_count'] > comparison_2['follower_count']):
                        print ("You are Right !! Great Going !!")
                        score += 1
                        print ()
                    elif (comparison_1['follower_count'] < comparison_2['follower_count']):
                        print ("Sorry, Your Guess was Wrong !! Try Again")
                        print (f"Your Score: {score}")
                        break    
                elif (make_a_choice == "B"):
                    if (comparison_1['follower_count'] < comparison_2['follower_count']):
                        print ("You are Right !! Great Going !!")
                        score += 1
                        print ()
                    elif (make_a_choice == "B" and (comparison_1['follower_count'] > comparison_2['follower_count'])):
                        print ("Sorry, Your Guess was Wrong !! Try Again")
                        print (f"Your Score: {score}")
                        break
                else: 
                    print ("Wrong Input.")
    
    print ("\nThank You For Playing !!")
    game = input("Press 'r' to Restart or 'q' to Quit: ")
    if (game == "r"):
        system_clean()
        play_game()
    elif (game == 'q'):
        print ("See You Again!!")
        
play_game()